import re


contractions = dict()
contractions['en'] = {
    "ain't": "am not",
    "aren't": "are not",
    "can't've": "cannot have",
    "can't": "cannot",
    "'cause": "because",
    "could've": "could have",
    "couldn't've": "could not have",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't've": "had not have",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd've": "he would have",
    "he'd": "he would",
    "he'll've": "he will have",
    "he'll": "he will",
    "he's": "he is",
    "how'd'y": "how do you",
    "how'd": "how did",
    "how'll": "how will",
    "how's": "how is",
    "i'd've": "i would have",
    "i'd": "i would",
    "i'll've": "i will have",
    "i'll": "i will",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd've": "it would have",
    "it'd": "it had",
    "it'll've": "it will have",
    "it'll": "it will",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't've": "might not have",
    "mightn't": "might not",
    "must've": "must have",
    "mustn't've": "must not have",
    "mustn't": "must not",
    "needn't've": "need not have",
    "needn't": "need not",
    "o'clock": "of the clock",
    "oughtn't've": "ought not have",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "shan't've": "shall not have",
    "sha'n't": "shall not",
    "she'd've": "she would have",
    "she'd": "she would",
    "she'll've": "she will have",
    "she'll": "she will",
    "she's": "she is",
    "should've": "should have",
    "shouldn't've": "should not have",
    "shouldn't": "should not",
    "so've": "so have",
    "so's": "so is",
    "that'd've": "that would have",
    "that'd": "that would",
    "that's": "that is",
    "there'd've": "there would have",
    "there'd": "there had",
    "there's": "there is",
    "they'd've": "they would have",
    "they'd": "they would",
    "they'll've": "they will have",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd've": "we would have",
    "we'd": "we had",
    "we'll've": "we will have",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll've": "what will have",
    "what'll": "what will",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll've": "who will have",
    "who'll": "who will",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't've": "will not have",
    "won't": "will not",
    "would've": "would have",
    "wouldn't've": "would not have",
    "wouldn't": "would not",
    "y'alls": "you alls",
    "y'all": "you all",
    "y'all'd've": "you all would have",
    "y'all'd": "you all would",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd've": "you would have",
    "you'd": "you had",
    "you'll've": "you you will have",
    "you'll": "you you will",
    "you're": "you are",
    "you've": "you have"
}
contractions['nl'] = {
    "m'n": "mijn",
    "z'n": "zijn",
    "zo'n": "zo een",
    "t'is": "het is",
    "da's": "dat is",
    "di's": "dit is",
    "d'r": "de haare",
    "h'r": "haar"
}


def replace_contractions(
        text: str,
        contractions: dict = contractions['en']) -> str:
    """
    Based on https://gist.github.com/nealrs/96342d8231b75cf4bb82

    :param:
        text: str
            Input text
        contractions: dict (default=contractions['en'])
            Dictionary of contractions (key) and their expanded forms (value).
    """
    p = re.compile(r'\b(%s)\b' % '|'.join(contractions.keys()))
    return p.sub(lambda match: contractions[match.group(0)], text.lower())
